version: '3.7'

services:
  todo-app:
    container_name: todo-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-services
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/services
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
